#+TITLE: Iyori's Customize File 
#+OPTIONS: toc:nil num:nil ^:nil

* Custmize Top

** 基本設定
*** 常時デバッグ状態
#+begin_src emacs-lisp
  (setq debug-on-error t)
#+end_src

*** Fonts
**** 文字コードの判別
#+begin_src emacs-lisp
; 言語を日本語にする
(set-language-environment "Japanese")
;; 文字コード
;(set-language-environment  'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(ansi-color-for-comint-mode-on)
;; 極力UTF-8とする
#+end_src

http://nijino.homelinux.net/emacs/emacs23-ja.html
#+begin_src emacs-lisp
  (cond
   ((not (string< mule-version "6.0"))
    ;; encode-translation-table の設定
    (coding-system-put 'euc-jp :encode-translation-table
                       (get 'japanese-ucs-cp932-to-jis-map 'translation-table))
    (coding-system-put 'iso-2022-jp :encode-translation-table
                       (get 'japanese-ucs-cp932-to-jis-map 'translation-table))
    (coding-system-put 'cp932 :encode-translation-table
                       (get 'japanese-ucs-jis-to-cp932-map 'translation-table))
    ;; charset と coding-system の優先度設定
    (set-charset-priority 'ascii 'japanese-jisx0208 'latin-jisx0201
                          'katakana-jisx0201 'iso-8859-1 'cp1252 'unicode)
    (set-coding-system-priority 'utf-8 'euc-jp 'iso-2022-jp 'cp932)))
#+end_src

**** フォントの設定
    * 英数部分に「Liberation Mono」
    * 日本語部分に「Takao ゴシック」
    * サイズは11となっている
#+begin_src emacs-lisp
  ;; Use Fonts
  (when window-system
    (progn
      (set-default-font "Liberation Mono-11")
      ;(set-frame-font "Courier 10 Pitch-12")
      (set-fontset-font (frame-parameter nil 'font)
                        'japanese-jisx0208
                        '("TakaoGothic" . "unicode-bmp"))))
#+end_src

*** Misc
**** ｘのクリップボードを使う設定
#+begin_src emacs-lisp
; make emacs use the clipboard
  (setq x-select-enable-clipboard t)
#+end_src

**** スクロールバーを表示しない
#+begin_src emacs-lisp
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+end_src

**** 時刻を表示する
#+begin_src emacs-lisp
(display-time)
#+end_src

**** スクロールのマージン
#+begin_src emacs-lisp
;; 一行ずつスクロールする
(setq scroll-conservatively 35)
(setq scroll-margin 0)
(setq scroll-step 1)
(setq comint-scroll-show-maximum-output 1)
;(setq next-screen-context-lines 3)
#+end_src

**** Tabの設定
#+begin_src emacs-lisp
;;インデントにタブを使わない
(setq-default indent-tabs-mode nil)
;; TAB はスペース 4 個ぶんを基本
(setq-default tab-width 4 indent-tabs-mode nil)
;;タブ幅の倍数を設定
(setq tab-stop-list
  '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60))
#+end_src

*** Server
**** シェルから現在のEmacsにアクセスする
#+begin_src emacs-lisp
  (server-start)
  (defun iconify-emacs-when-server-is-done ()
    (unless server-clients (iconify-frame)))
  ;; 編集が終了したらEmacsをアイコン化する
  ;;(add-hook 'server-done-hook 'iconify-emacs-when-server-is-done)
  ;; C-x C-cに割り当てる
  (global-set-key (kbd "C-x C-c") 'server-edit)
  ;; M-x exit でEmacsを終了できるようにする
  (defalias 'exit 'save-buffer-kill-emacs)
#+end_src
*** Color Theme
**** カラーテーマを選択
 [[file:starter-kit-miac.org][ starter-kit-misc]] に設定が書いてある。
#+begin_src emacs-lisp :tangle no
  ; Color Theme
  (color-theme-example)
#+end_src
**** 半透明化とサイズと色指定
http://d.hatena.ne.jp/goryugo/20081017/1224174326

#+begin_src emacs-lisp
  (setq default-frame-alist
        (setq initial-frame-alist
              (append (list
                       '(foreground-color . "azure3")
                       '(background-color . "black")
                       '(mouse-color . "white")
                       '(alpha . (85 80 60 60))
                       '(width . 100)
                       ;;'(height . 47)
                       ;;'(width . 60)
                       '(height . 40)
                       ) initial-frame-alist)))
#+end_src


** vendor lisps
*** setting auto-install.el
http://d.hatena.ne.jp/rubikitch/20091221/autoinstall
http://www.emacswiki.org/AutoInstall
#+begin_src emacs-lisp
  (require 'auto-install)
  (setq auto-install-directory (concat dotfiles-dir "auto-install"))
  (add-to-list 'load-path (expand-file-name "auto-install" dotfiles-dir))
  (auto-install-update-emacswiki-package-name t)
  (auto-install-compatibility-setup)             ; 互換性確保
#+end_src

*** setting auto-complete.el
■ミラーページ
(shell-command "x-www-browser https://github.com/m2ym/auto-complete")
■リポジトリを更新
(shell-command (concat "terminator --working-directory=" vendor-dir "auto-complete" " | git pull"))
自動補完 (~/emacs.d/etc/auto-complete)
auto complete (http://dev.ariel-networks.com/Members/matsuyama/auto-complete)
M-x auto-complete-modeで有効化
TAB: 補完を実行する
C-n/<down>: 次の候補
C-p/<up>: 前の候補
C-m/RET:補完完了

#+begin_src emacs-lisp
  (add-to-list 'load-path
                 (expand-file-name "auto-complete"
                                   (expand-file-name "src" dotfiles-dir)))
  (require 'auto-complete-config)
  (add-to-list 'ac-dictionary-directories
               (expand-file-name "dict"
                                 (expand-file-name "auto-complete"
                                                   (expand-file-name "src" dotfiles-dir))))
  (ac-config-default)
#+end_src

*** setting ibus-mozc of ibus.el

site
http://d.hatena.ne.jp/iRiE/20100529/1275162812
■ wiki
http://www11.atwiki.jp/s-irie/pages/21.html
■ ppa
https://launchpad.net/~irie/+archive/elisp

iBusはデフォルトでは Ctrl-Space でオンオフを切り替えられるようになっている、
EmacsのMark setと重複しているため、それを無効にする。
そして Ctrl-\ でIBusが起動するようにする。ついでにカーソルの色も変更。

#+begin_src emacs-lisp
  (require 'ibus)
  ;; Turn on ibus-mode automatically after loading .emacs
  (add-hook 'after-init-hook 'ibus-mode-on)
  ;; Use C-SPC for Set Mark command
  (ibus-define-common-key ?\C-s nil)
  ;; Use C-/ for Undo command
  (ibus-define-common-key ?\C-\/ nil)
  ;; Change cursor color depending on IBus status
  (setq ibus-cursor-color '("red" "white" "blue"))
  ;; 変換候補表示中のカーソルの位置および形状を変える
  (setq ibus-cursor-type-for-candidate 0)
  (setq ibus-put-cursor-on-candidate nil)
  ;; C-\ で半角英数モードをトグルする
  (global-set-key "\C-\\" 'ibus-toggle)
  ;; 予測候補ウィンドウの表示位置の変更
  (setq ibus-prediction-window-position t)
#+end_src

*** setting tabbar.el
- タブ表示
  -タブ選択: マウスクリック，Ctrl-, Ctrl-.
  - 表示・非表示の変更: F4
- バッファ状態復元
   o 状態復元: Ctrl-x F
   o 状態保存: Ctrl-x S または Emacs 終了時
sites
http://d.hatena.ne.jp/alfad/20100425/1272208744
http://www.emacswiki.org/cgi-bin/wiki/TabBarMode
http://d.hatena.ne.jp/katsu_w/20080319/1205923300
http://sourceforge.net/projects/emhacks/files/


**** グループ化せずに*scratch*以外のタブを表示
#+begin_src emacs-lisp
  (when (require 'tabbar nil t)
    (setq tabbar-buffer-groups-function
          (lambda () (list "All Buffers")))
    (setq tabbar-buffer-list-function
          (lambda ()
            (remove-if
             (lambda(buffer)
               (find (aref (buffer-name buffer) 0) " *"))
             (buffer-list))))
    (tabbar-mode))
#+end_src

**** 左に表示されるボタンを無効化
#+begin_src emacs-lisp
  ;;(setq tabbar-home-button-enabled "")
  ;;(setq tabbar-scroll-left-button-enabled "")
  ;;(setq tabbar-scroll-right-button-enabled "")
  ;;(setq tabbar-scroll-left-button-disabled "")
  ;;(setq tabbar-scroll-right-button-disabled "")
#+end_src

**** 色設定
#+begin_src emacs-lisp
  (set-face-attribute
    'tabbar-default nil
    :background "grey90") ;バー自体の色
   (set-face-attribute ;非アクティブなタブ
    'tabbar-unselected nil
    :background "grey80"
    :foreground "grey40"
    :box nil)
   (set-face-attribute ;アクティブなタブ
    'tabbar-selected nil
    :background "grey50"
    :foreground "black"
    :box nil)
   (set-face-attribute
    'tabbar-button nil
    :box '(:line-width 1 :color "gray72" :style released-button))
#+end_src

**** 幅設定
#+begin_src emacs-lisp
  (set-face-attribute  'tabbar-separator nil
                       :height 0.7)
#+end_src

**** キーバインド F4 で tabbar-mode
#+begin_src emacs-lisp
(global-set-key (kbd "C-,") 'tabbar-backward)
(global-set-key (kbd "C-.") 'tabbar-forward)
(global-set-key (kbd "<f4>") 'tabbar-mode)
#+end_src

*** setting windows.el & revive.el
;; key bind  Edit
;; C-c C-w 1	分割状態 1 へ (Q)
;; C-c C-w 2	分割状態 2 へ (Q)
;; C-c C-w 9	分割状態 9 へ (Q)
;; C-c C-w 0	直前の分割状態へ(バッファ0と交換) (Q)
;; C-c C-w SPC	分割状態1～nのうち、直前用いたものへ (Q)
;; C-c C-w n	次の分割状態へ(C-c SPC)
;; C-c C-w p	前の分割状態へ
;; C-c C-w !	現在のウィンドウを破棄 (Q)
;; C-c C-w -	ちょっと前のウィンドウ状態を復活(Q)
;; C-c C-w C-w	ウィンドウ操作メニュー
;; C-c C-w C-r	リジュームメニュー
;; C-c C-w C-l	ローカルリジュームメニュー
;; C-c C-w C-s	タスク切替え
;; C-c C-w =	分割状態保存バッファ一覧表示 (Q)

;; デフォルトの設定ではQマークの付いているkey bindはC-wを省略できます。
http://technique.sonots.com/?UNIX%2F%E5%AD%A6%E7%94%9F%E3%83%84%E3%83%BC%E3%83%AB%2Felisp%2Fwindows.el
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
**** windows.el
(require 'windows)
(win:startup-with-window)
(define-key ctl-x-map "C" 'see-you-again)

**** revive.el
#+begin_src emacs-lisp
  (require 'revive)
  (autoload 'save-current-configuration "revive" "Save status" t)
  (autoload 'resume "revive" "Resume Emacs" t)
  (autoload 'wipe "revive" "Wipe emacs" t)
  (define-key ctl-x-map "F" 'resume)                        ; C-x F で復元
  (define-key ctl-x-map "K" 'wipe)                          ; C-x K で Kill
  (add-hook 'kill-emacs-hook 'save-current-configuration)   ; 終了時に状態保存
  (resume) ; 起動時に復元
#+end_src

*** setting jaspace.el
■ タブ, 全角スペース、改行直前の半角スペースを表示する
(find-file-other-window (concat dotfiles-dir "src/jaspace.el"))

jaspace.el を使った全角空白、タブ、改行表示モード
切り替えは M-x jaspace-mode-on or -off

■ ここで配布されている
http://homepage3.nifty.com/satomii/software/elisp.ja.html
http://homepage3.nifty.com/satomii/software/jaspace.el
http://ubulog.blogspot.com/2007/09/emacs_09.html

■ 設定ファイルとか
http://openlab.dino.co.jp/2008/08/29/230500336.html

#+begin_src emacs-lisp
    (when (require 'jaspace nil t)
      (when (boundp 'jaspace-modes)
        (setq jaspace-modes (append jaspace-modes
                                    (list 'php-mode
                                          'yaml-mode
                                          'javascript-mode
                                          'ruby-mode
                                          'text-mode
                                          'fundamental-mode
                                          'python-mode))))
      (when (boundp 'jaspace-alternate-jaspace-string)
        (setq jaspace-alternate-jaspace-string "□"))
      (when (boundp 'jaspace-highlight-tabs)
        (setq jaspace-highlight-tabs ?^))
      (when (boundp 'jaspace-alternate-eol-string)
        (setq jaspace-alternate-eol-string "↓\n"))
      (add-hook 'jaspace-mode-off-hook
                (lambda()
                  (when (boundp 'show-trailing-whitespace)
                    (setq show-trailing-whitespace nil))))
      (add-hook 'jaspace-mode-hook
                (lambda()
                  (progn
                    (when (boundp 'show-trailing-whitespace)
                      (setq show-trailing-whitespace t))
                    (face-spec-set 'jaspace-highlight-jaspace-face
                                   '((((class color) (background light))
                                      (:foreground "blue"))
                                     (t (:foreground "green"))))
                    (face-spec-set 'jaspace-highlight-tab-face
                                   '((((class color) (background light))
                                      (:foreground "red"
                                       :background "unspecified"
                                       :strike-through nil
                                       :underline t))
                                     (t (:foreground "purple"
                                         :background "unspecified"
                                         :strike-through nil
                                         :underline t))))
                    (face-spec-set 'trailing-whitespace
                                   '((((class color) (background light))
                                      (:foreground "red"
                                       :background "unspecified"
                                       :strike-through nil
                                       :underline t))
                                     (t (:foreground "purple"
                                         :background "unspecified"
                                         :strike-through nil
                                         :underline t))))))))
  (add-hook 'find-file-hook 'jaspace-mode)
#+end_src
